// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const INCREMENT_COUNTER_IF_ODD = 'INCREMENT_COUNTER_IF_ODD'


export const REQUEST_LOCATIONS = 'REQUEST_LOCATIONS';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';



